// Japanese labels for FMP field keys shown on the data-probe page.
// Keys are shared across the quote / profile / ratios / key-metrics /
// income-statement / history endpoints. Unmapped keys fall back to the raw key.

const FIELD_LABELS: Record<string, string> = {
  // --- 共通 ---
  symbol: "シンボル",
  name: "銘柄名",
  date: "基準日",
  period: "期間",
  fiscalYear: "会計年度",
  reportedCurrency: "報告通貨",
  currency: "通貨",
  exchange: "取引所",
  exchangeFullName: "取引所(正式名)",

  // --- quote ---
  price: "株価",
  changePercentage: "騰落率(%)",
  change: "前日比",
  volume: "出来高",
  dayLow: "当日安値",
  dayHigh: "当日高値",
  yearHigh: "52週高値",
  yearLow: "52週安値",
  marketCap: "時価総額",
  priceAvg50: "50日平均株価",
  priceAvg200: "200日平均株価",
  open: "始値",
  previousClose: "前日終値",
  timestamp: "タイムスタンプ",

  // --- profile ---
  beta: "ベータ",
  lastDividend: "直近配当",
  range: "価格レンジ(52週)",
  averageVolume: "平均出来高",
  companyName: "会社名",
  cik: "CIK(米SEC企業コード)",
  isin: "ISINコード",
  cusip: "CUSIP(米証券コード)",
  industry: "業種",
  website: "ウェブサイト",
  description: "企業概要",
  ceo: "CEO",
  sector: "セクター",
  country: "国",
  fullTimeEmployees: "従業員数",
  phone: "電話番号",
  address: "住所",
  city: "市区町村",
  state: "州",
  zip: "郵便番号",
  image: "ロゴ画像",
  ipoDate: "上場日",
  defaultImage: "デフォルト画像",
  isEtf: "ETFか",
  isActivelyTrading: "取引中か",
  isAdr: "ADRか",
  isFund: "ファンドか",

  // --- ratios ---
  grossProfitMargin: "売上総利益率",
  ebitMargin: "EBITマージン",
  ebitdaMargin: "EBITDAマージン",
  operatingProfitMargin: "営業利益率",
  pretaxProfitMargin: "税引前利益率",
  continuousOperationsProfitMargin: "継続事業利益率",
  netProfitMargin: "純利益率",
  bottomLineProfitMargin: "最終利益率",
  receivablesTurnover: "売上債権回転率",
  payablesTurnover: "仕入債務回転率",
  inventoryTurnover: "棚卸資産回転率",
  fixedAssetTurnover: "固定資産回転率",
  assetTurnover: "総資産回転率",
  currentRatio: "流動比率",
  quickRatio: "当座比率",
  solvencyRatio: "支払能力比率",
  cashRatio: "現金比率",
  priceToEarningsRatio: "PER(株価収益率)",
  priceToEarningsGrowthRatio: "PEGレシオ",
  forwardPriceToEarningsGrowthRatio: "予想PEGレシオ",
  priceToBookRatio: "PBR(株価純資産倍率)",
  priceToSalesRatio: "PSR(株価売上高倍率)",
  priceToFreeCashFlowRatio: "株価フリーCF倍率",
  priceToOperatingCashFlowRatio: "株価営業CF倍率",
  debtToAssetsRatio: "負債資産比率",
  debtToEquityRatio: "D/Eレシオ(負債資本倍率)",
  debtToCapitalRatio: "負債資本構成比率",
  longTermDebtToCapitalRatio: "長期負債資本構成比率",
  financialLeverageRatio: "財務レバレッジ",
  workingCapitalTurnoverRatio: "運転資本回転率",
  operatingCashFlowRatio: "営業CF比率",
  operatingCashFlowSalesRatio: "営業CF売上高比率",
  freeCashFlowOperatingCashFlowRatio: "フリーCF対営業CF比率",
  debtServiceCoverageRatio: "債務返済能力比率",
  interestCoverageRatio: "インタレストカバレッジレシオ",
  shortTermOperatingCashFlowCoverageRatio: "短期営業CFカバレッジ",
  operatingCashFlowCoverageRatio: "営業CFカバレッジ",
  capitalExpenditureCoverageRatio: "設備投資カバレッジ",
  dividendPaidAndCapexCoverageRatio: "配当・設備投資カバレッジ",
  dividendPayoutRatio: "配当性向",
  dividendYield: "配当利回り",
  dividendYieldPercentage: "配当利回り(%)",
  revenuePerShare: "1株当たり売上高",
  netIncomePerShare: "1株当たり純利益",
  interestDebtPerShare: "1株当たり有利子負債",
  cashPerShare: "1株当たり現金",
  bookValuePerShare: "1株当たり純資産(BPS)",
  tangibleBookValuePerShare: "1株当たり有形純資産",
  shareholdersEquityPerShare: "1株当たり株主資本",
  operatingCashFlowPerShare: "1株当たり営業CF",
  capexPerShare: "1株当たり設備投資",
  freeCashFlowPerShare: "1株当たりフリーCF",
  netIncomePerEBT: "純利益/税引前利益",
  ebtPerEbit: "税引前利益/EBIT",
  priceToFairValue: "株価/適正価値",
  debtToMarketCap: "負債/時価総額",
  effectiveTaxRate: "実効税率",
  enterpriseValueMultiple: "EV倍率",
  dividendPerShare: "1株当たり配当(DPS)",

  // --- key-metrics ---
  enterpriseValue: "企業価値(EV)",
  evToSales: "EV/売上高",
  evToOperatingCashFlow: "EV/営業CF",
  evToFreeCashFlow: "EV/フリーCF",
  evToEBITDA: "EV/EBITDA",
  netDebtToEBITDA: "純有利子負債/EBITDA",
  incomeQuality: "利益の質",
  grahamNumber: "グレアム数",
  grahamNetNet: "グレアム・ネットネット",
  taxBurden: "税負担率",
  interestBurden: "利息負担率",
  workingCapital: "運転資本",
  investedCapital: "投下資本",
  returnOnAssets: "ROA(総資産利益率)",
  operatingReturnOnAssets: "営業ROA",
  returnOnTangibleAssets: "有形資産利益率",
  returnOnEquity: "ROE(自己資本利益率)",
  returnOnInvestedCapital: "ROIC(投下資本利益率)",
  returnOnCapitalEmployed: "ROCE(使用資本利益率)",
  earningsYield: "益回り",
  freeCashFlowYield: "フリーCF利回り",
  capexToOperatingCashFlow: "設備投資/営業CF",
  capexToDepreciation: "設備投資/減価償却",
  capexToRevenue: "設備投資/売上高",
  salesGeneralAndAdministrativeToRevenue: "販管費/売上高",
  researchAndDevelopementToRevenue: "研究開発費/売上高",
  stockBasedCompensationToRevenue: "株式報酬/売上高",
  intangiblesToTotalAssets: "無形資産/総資産",
  averageReceivables: "平均売上債権",
  averagePayables: "平均仕入債務",
  averageInventory: "平均棚卸資産",
  daysOfSalesOutstanding: "売上債権回転日数",
  daysOfPayablesOutstanding: "仕入債務回転日数",
  daysOfInventoryOutstanding: "棚卸資産回転日数",
  operatingCycle: "営業サイクル(日数)",
  cashConversionCycle: "現金循環化日数(CCC)",
  freeCashFlowToEquity: "株主帰属フリーCF(FCFE)",
  freeCashFlowToFirm: "企業フリーCF(FCFF)",
  tangibleAssetValue: "有形資産価値",
  netCurrentAssetValue: "正味流動資産価値",

  // --- income-statement ---
  filingDate: "提出日",
  acceptedDate: "受理日時",
  revenue: "売上高",
  costOfRevenue: "売上原価",
  grossProfit: "売上総利益",
  researchAndDevelopmentExpenses: "研究開発費",
  generalAndAdministrativeExpenses: "一般管理費",
  sellingAndMarketingExpenses: "販売・マーケティング費",
  sellingGeneralAndAdministrativeExpenses: "販管費",
  otherExpenses: "その他費用",
  operatingExpenses: "営業費用",
  costAndExpenses: "費用合計",
  netInterestIncome: "純利息収益",
  interestIncome: "受取利息",
  interestExpense: "支払利息",
  depreciationAndAmortization: "減価償却費",
  ebitda: "EBITDA",
  ebit: "EBIT",
  nonOperatingIncomeExcludingInterest: "営業外収益(利息除く)",
  operatingIncome: "営業利益",
  totalOtherIncomeExpensesNet: "その他損益(純額)",
  incomeBeforeTax: "税引前利益",
  incomeTaxExpense: "法人税等",
  netIncomeFromContinuingOperations: "継続事業純利益",
  netIncomeFromDiscontinuedOperations: "非継続事業純利益",
  otherAdjustmentsToNetIncome: "純利益その他調整",
  netIncome: "純利益",
  netIncomeDeductions: "純利益控除",
  bottomLineNetIncome: "最終純利益",
  eps: "EPS(1株当たり利益)",
  epsDiluted: "希薄化EPS",
  weightedAverageShsOut: "加重平均発行株式数",
  weightedAverageShsOutDil: "加重平均発行株式数(希薄化後)",

  // --- history (summary) ---
  bars: "取得本数(営業日)",
  from: "開始日",
  to: "終了日",
  lastClose: "直近終値",
  lastVolume: "直近出来高",
};

/** Japanese label for an FMP field key; falls back to the raw key. */
export function labelFor(key: string): string {
  return FIELD_LABELS[key] || key;
}
